server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos.test.com:80
    gateway:
      discovery:
        locator:
          enabled: true  # 让gateway可以发现nacos中的微服务
      routes: # 路由数组,路由就是指定当请求满足什么条件的时候，转到 哪个微服务
        - id: servicea  # 路由的Id，没有固定规则，但要求唯一，建议配合服务名
          #          uri: http://localhost:9083 # 匹配后，请求转发到的地址
          uri: lb://serviceb # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
          predicates: # 断言：就是路由转发要满足的条件
            - Path=/hellob/**